[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
bitfields = "3.1.0"
bitflags = "2.13.2"
bytemuck = { version = "1.25.2", features = ["derive"] }
flanterm = "0.0.2"
interrupts = "=0.2.0"
intrusive-collections = "0.10.3"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
limine = "0.6.5"
linked_list_allocator = "0.10.6"
num_enum = { version = "0.7.6", default-features = false }
spin = "0.12.3"
tar-no-std = "0.4.2"



[profile.release]
panic = "abort"


[profile.dev]
panic = "abort"

[lib]
test = false

[[bin]]
name = "kernel"
test = false
doctest = false
bench = false
