[tasks.clean]



[tasks.build]
dependencies = ["build-kernel", "copy-bin", "create-image"]
[tasks.run]

[tasks.build-kernel]
command = "cargo"
args = ["build"]


[tasks.copy-bin]
command = "cp"
args = ["-f", "target/${CARGO_MAKE_RUST_TARGET_ARCH}-unknown-none/debug/kernel", "../bin"]


[tasks.clone-limine]
condition = { files_not_exist = ["./limine"]}
command = "git"
args = ["clone", "https://github.com/Limine-Bootloader/Limine.git", "--branch", "v11.x-binary", "limine"]

[tasks.build-limine]
cwd = "limine"
command = "make"

[tasks.create-iso-root]
command = "mkdir"
args = ["-p", "iso_root"]

[tasks.copy-limine-files]
script = '''
    mkdir -p iso_root/boot
    cp -v ../bin/kernel iso_root/boot/
    mkdir -p iso_root/boot/limine
    cp -v ../limine.conf limine/limine-bios.sys limine/limine-bios-cd.bin \
        limine/limine-uefi-cd.bin iso_root/boot/limine/

'''

[tasks.create-efi-boot]
script = ''' 
    mkdir -p iso_root/EFI/BOOT
    cp -v limine/BOOTX64.EFI iso_root/EFI/BOOT/
    cp -v limine/BOOTIA32.EFI iso_root/EFI/BOOT/
'''

[tasks.create-iso]
command = "xorriso"
args = ["-as", "mkisofs", "-R", "-r", "-J", "-b", "boot/limine/limine-bios-cd.bin", "-no-emul-boot", "-boot-load-size", "4", "-boot-info-table", "-hfsplus",
        "-apm-block-size", "2048", "--efi-boot", "boot/limine/limine-uefi-cd.bin", "-efi-boot-part", "--efi-boot-image", "--protective-msdos-label",
        "iso_root", "-o", "../image.iso"]
[tasks.install-limine]
command = "./limine/limine"
args = ["bios-install", "../image.iso"]

[tasks.create-image]
#condition = { files_not_exist = ["../image.iso"]}
dependencies = ["clone-limine", "build-limine", "create-iso-root", "copy-limine-files","create-efi-boot", "create-iso"]



[tasks.test]
disabled = true


